[project]
name = "building-with-the-claude-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tam Huynh", email = "tam.huynh@elinext.com" }
]
requires-python = ">=3.14"
dependencies = [
    "anthropic>=0.121.0",
    "dotenv>=0.9.9",
    "voyageai",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.8",
]
